server:
  port: 9000
  error:
    include-stacktrace: never
spring:
  datasource:
    url: jdbc:postgresql://34.89.149.252/postgres?sslmode=require
    username: postgres
    password: 3Ani,VenerabileMaestru!
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
logging:
  level:
    org:
      odftoolkit: OFF